# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_s4Wb_pK7yf4YvFYOd_0aomkBEwE7nU
"""

import os
import re
import json
import pickle
import subprocess
import pandas as pd
import streamlit as st
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

st.set_page_config(page_title="Spam Detection Platform", page_icon="📧", layout="wide")

# -----------------------------
# AUTO-TRAIN (FIX FOR GITHUB LIMIT)
# -----------------------------
if not os.path.exists("models/best_model.pkl"):
    st.warning("⚙️ First run: Training model... please wait (1–2 minutes)")
    subprocess.run(["python", "train_model.py"])

# -----------------------------
# PATHS
# -----------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, "models")
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
CM_DIR = os.path.join(ASSETS_DIR, "confusion_matrices")

CUSTOM_STOPWORDS = set(ENGLISH_STOP_WORDS)

# -----------------------------
# CLEANING FUNCTION
# -----------------------------
def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    tokens = [w for w in text.split() if w not in CUSTOM_STOPWORDS]
    return " ".join(tokens)

# -----------------------------
# LOAD MODELS
# -----------------------------
@st.cache_resource
def load_resources():
    with open(os.path.join(MODELS_DIR, "all_models.pkl"), "rb") as f:
        all_models = pickle.load(f)

    with open(os.path.join(MODELS_DIR, "vectorizer.pkl"), "rb") as f:
        vectorizer = pickle.load(f)

    with open(os.path.join(MODELS_DIR, "metadata.json"), "r") as f:
        metadata = json.load(f)

    results_df = pd.read_csv(os.path.join(ASSETS_DIR, "comparison_results.csv"))

    return all_models, vectorizer, metadata, results_df

# -----------------------------
# PREDICTION
# -----------------------------
def predict_message(text, selected_key, all_models, vectorizer):
    clean_msg = clean_text(text)
    X = vectorizer.transform([clean_msg]).toarray()

    model = all_models[selected_key]
    pred = int(model.predict(X)[0])

    confidence = None
    if hasattr(model, "predict_proba"):
        confidence = float(model.predict_proba(X).max())

    return pred, confidence, clean_msg

# -----------------------------
# MAIN APP
# -----------------------------
def main():
    all_models, vectorizer, metadata, results_df = load_resources()

    best_key = metadata["best_model_key"]
    dataset_summary = metadata["dataset_summary"]

    st.title("📧 Spam Detection Platform")
    st.caption("Advanced Business Analytics Project | Live classification, model comparison, SMOTE analysis, and insights")

    tab1, tab2, tab3 = st.tabs(["🔍 Live Classifier", "📊 Model Comparison", "☁️ Insights"])

    # -----------------------------
    # TAB 1
    # -----------------------------
    with tab1:
        col1, col2 = st.columns([1.5, 1])

        with col1:
            st.subheader("Classify a Message")

            model_options = list(all_models.keys())
            default_index = model_options.index(best_key)

            selected_model_key = st.selectbox(
                "Choose model",
                model_options,
                index=default_index
            )

            st.session_state.setdefault("message_box", "")

            c1, c2, c3 = st.columns(3)

            with c1:
                if st.button("Use Spam Example"):
                    st.session_state["message_box"] = "Congratulations! You have won a free iPhone. Click now!"

            with c2:
                if st.button("Use Valid Example"):
                    st.session_state["message_box"] = "Hi Mohammed, please review the meeting agenda."

            with c3:
                if st.button("Clear Text"):
                    st.session_state["message_box"] = ""

            user_text = st.text_area("Enter message", key="message_box", height=150)

            if st.button("Classify Message", use_container_width=True):
                if not user_text.strip():
                    st.warning("Please enter text")
                else:
                    pred, conf, cleaned = predict_message(
                        user_text, selected_model_key, all_models, vectorizer
                    )

                    st.markdown("---")

                    if pred == 1:
                        st.error(f"🚨 Spam ({conf:.2%})")
                    else:
                        st.success(f"✅ Valid ({conf:.2%})")

                    st.info(f"Model used: {selected_model_key}")

        with col2:
            st.subheader("Project Snapshot")

            st.metric("Total Messages", dataset_summary["rows"])
            st.metric("Valid", dataset_summary["valid_count"])
            st.metric("Spam", dataset_summary["spam_count"])

            st.markdown("### Best Model")
            st.write(best_key)
            st.write(f"F1: {metadata['best_f1']}")

    # -----------------------------
    # TAB 2
    # -----------------------------
    with tab2:
        st.subheader("Model Comparison")
        st.dataframe(results_df)

    # -----------------------------
    # TAB 3
    # -----------------------------
    with tab3:
        st.subheader("Insights")

        valid_wc = os.path.join(ASSETS_DIR, "valid_wordcloud.png")
        spam_wc = os.path.join(ASSETS_DIR, "spam_wordcloud.png")

        col1, col2 = st.columns(2)

        if os.path.exists(valid_wc):
            col1.image(valid_wc, caption="Valid Messages")

        if os.path.exists(spam_wc):
            col2.image(spam_wc, caption="Spam Messages")

# -----------------------------
if __name__ == "__main__":
    main()