# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_s4Wb_pK7yf4YvFYOd_0aomkBEwE7nU
"""

import os
import re
import json
import pickle
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from wordcloud import WordCloud
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
)
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

warnings.filterwarnings("ignore")

RANDOM_STATE = 42
MAX_FEATURES = 3000

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(BASE_DIR, "Project file.csv")
MODELS_DIR = os.path.join(BASE_DIR, "models")
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
CM_DIR = os.path.join(ASSETS_DIR, "confusion_matrices")

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(ASSETS_DIR, exist_ok=True)
os.makedirs(CM_DIR, exist_ok=True)

CUSTOM_STOPWORDS = set(ENGLISH_STOP_WORDS)

LABEL_MAP = {
    "spam": 1,
    "ham": 0,
    "valid": 0,
}


def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", " ", text)      # remove hyperlinks
    text = re.sub(r"\d+", " ", text)                 # remove numbers
    text = re.sub(r"[^a-z\s]", " ", text)            # remove special characters
    text = re.sub(r"\s+", " ", text).strip()         # remove extra whitespaces
    tokens = [w for w in text.split() if w not in CUSTOM_STOPWORDS]
    return " ".join(tokens)


def save_wordcloud(text_series: pd.Series, output_path: str, title: str) -> None:
    text_blob = " ".join(text_series.dropna().astype(str))
    if not text_blob.strip():
        return

    wc = WordCloud(width=1200, height=600, background_color="white").generate(text_blob)
    plt.figure(figsize=(12, 6))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    plt.title(title, fontsize=16)
    plt.tight_layout()
    plt.savefig(output_path, bbox_inches="tight")
    plt.close()


def plot_conf_matrix(cm, labels, output_path, title):
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    fig, ax = plt.subplots(figsize=(5, 4))
    disp.plot(ax=ax, colorbar=False)
    ax.set_title(title)
    plt.tight_layout()
    plt.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def evaluate_model(model, X_train, y_train, X_test, y_test, model_name, scenario_name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    metrics = {
        "Scenario": scenario_name,
        "Model": model_name,
        "Accuracy": round(accuracy_score(y_test, y_pred), 4),
        "Precision": round(precision_score(y_test, y_pred, zero_division=0), 4),
        "Recall": round(recall_score(y_test, y_pred, zero_division=0), 4),
        "F1": round(f1_score(y_test, y_pred, zero_division=0), 4),
    }

    cm = confusion_matrix(y_test, y_pred)
    cm_filename = f"{scenario_name.lower().replace(' ', '_')}_{model_name.lower().replace(' ', '_')}.png"
    cm_path = os.path.join(CM_DIR, cm_filename)
    plot_conf_matrix(cm, ["Valid", "Spam"], cm_path, f"{model_name} - {scenario_name}")

    return model, metrics, cm_filename


def get_models():
    return {
        "Naive Bayes": MultinomialNB(),
        "KNN": KNeighborsClassifier(n_neighbors=5),
        "Logistic Regression": LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
        "Random Forest": RandomForestClassifier(
            n_estimators=200,
            random_state=RANDOM_STATE,
            n_jobs=-1,
        ),
    }


def main():
    # 1) Load data
    df = pd.read_csv(DATA_PATH)

    # Keep only required columns
    df = df.loc[:, [col for col in df.columns if col in ["class", "message"]]].copy()

    if "class" not in df.columns or "message" not in df.columns:
        raise ValueError("CSV must contain 'class' and 'message' columns.")

    df["class"] = df["class"].astype(str).str.strip().str.lower()
    df["class"] = df["class"].map(LABEL_MAP)

    df = df.dropna(subset=["class", "message"]).copy()
    df["class"] = df["class"].astype(int)
    df["clean_message"] = df["message"].apply(clean_text)

    # Dataset summary
    class_counts = df["class"].value_counts().to_dict()
    dataset_summary = {
        "rows": int(len(df)),
        "valid_count": int(class_counts.get(0, 0)),
        "spam_count": int(class_counts.get(1, 0)),
        "valid_pct": round(float((df["class"] == 0).mean() * 100), 2),
        "spam_pct": round(float((df["class"] == 1).mean() * 100), 2),
    }

    # 2) Word clouds
    save_wordcloud(
        df.loc[df["class"] == 0, "clean_message"],
        os.path.join(ASSETS_DIR, "valid_wordcloud.png"),
        "Valid Messages Word Cloud",
    )
    save_wordcloud(
        df.loc[df["class"] == 1, "clean_message"],
        os.path.join(ASSETS_DIR, "spam_wordcloud.png"),
        "Spam Messages Word Cloud",
    )

    # 3) Train/test split
    X_train_text, X_test_text, y_train, y_test = train_test_split(
        df["clean_message"],
        df["class"],
        test_size=0.2,
        random_state=RANDOM_STATE,
        stratify=df["class"],
    )

    # 4) TF-IDF
    vectorizer = TfidfVectorizer(max_features=MAX_FEATURES)
    X_train = vectorizer.fit_transform(X_train_text)
    X_test = vectorizer.transform(X_test_text)

    X_train_dense = X_train.toarray().astype(np.float32)
    X_test_dense = X_test.toarray().astype(np.float32)

    results = []
    trained_models = {}

    # 5) Before SMOTE
    for model_name, model in get_models().items():
        fitted_model, metrics, _ = evaluate_model(
            model=model,
            X_train=X_train_dense,
            y_train=y_train,
            X_test=X_test_dense,
            y_test=y_test,
            model_name=model_name,
            scenario_name="Before SMOTE",
        )
        results.append(metrics)
        trained_models[f"Before SMOTE::{model_name}"] = fitted_model

    # 6) After SMOTE
    smote = SMOTE(random_state=RANDOM_STATE)
    X_train_smote, y_train_smote = smote.fit_resample(X_train_dense, y_train)

    for model_name, model in get_models().items():
        fitted_model, metrics, _ = evaluate_model(
            model=model,
            X_train=X_train_smote,
            y_train=y_train_smote,
            X_test=X_test_dense,
            y_test=y_test,
            model_name=model_name,
            scenario_name="After SMOTE",
        )
        results.append(metrics)
        trained_models[f"After SMOTE::{model_name}"] = fitted_model

    # 7) Save comparison results
    results_df = pd.DataFrame(results).sort_values(
        by=["Scenario", "F1", "Recall", "Accuracy"],
        ascending=[True, False, False, False]
    )
    results_df.to_csv(os.path.join(ASSETS_DIR, "comparison_results.csv"), index=False)

    # 8) Select best model
    best_row = results_df.sort_values(
        by=["F1", "Recall", "Accuracy"],
        ascending=False
    ).iloc[0]

    best_key = f"{best_row['Scenario']}::{best_row['Model']}"
    best_model = trained_models[best_key]

    # 9) Save models
    with open(os.path.join(MODELS_DIR, "best_model.pkl"), "wb") as f:
        pickle.dump(best_model, f)

    with open(os.path.join(MODELS_DIR, "all_models.pkl"), "wb") as f:
        pickle.dump(trained_models, f)

    with open(os.path.join(MODELS_DIR, "vectorizer.pkl"), "wb") as f:
        pickle.dump(vectorizer, f)

    # 10) Save metadata
    metadata = {
        "best_model_key": best_key,
        "best_model_name": str(best_row["Model"]),
        "best_model_scenario": str(best_row["Scenario"]),
        "best_f1": float(best_row["F1"]),
        "dataset_summary": dataset_summary,
    }

    with open(os.path.join(MODELS_DIR, "metadata.json"), "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print("A+ version training completed successfully.")
    print(f"Best model: {metadata['best_model_key']} (F1={metadata['best_f1']})")
    print("Files saved to:")
    print(f"- {MODELS_DIR}")
    print(f"- {ASSETS_DIR}")


if __name__ == "__main__":
    main()